vich_uploader:
  db_driver: orm

  metadata:
    type: attribute

  mappings:

    menu_item_img:
      uri_prefix: /menu_item_img
      upload_destination: '%kernel.project_dir%/public/upload/menu_item_img'
      namer: Vich\UploaderBundle\Naming\SmartUniqueNamer